### ISSUE TITLE
Typo in Assignment1 task 2

### ISSUE THREAD

**Issue by rferens** [janchorowski/dl_uwr#2]
> [1p] Prepare the data for logistic regression: Map the sentiment scores $0,1,2,3,4$ to a probability of **the sentence being by setting** $p(\textrm{positive}) = \textrm{sentiment}/4$. Build a dictionary of at most 20000 most frequent words.

Should the bolded fragment be "sentence being positive"? It that probability a purpose of our logistic regression prediction(i.e. do we reduce orginally stated problem with scale 0-4 to just positive/negative classification)?

Morover, it seems that there is less than 20000 words in that sentences.

**Comment by janchorowski** [comment]
Yes about the typo, please submit a PR. 
WRT the number of words, that's great then, you can add an "if needed phrase", it is good practice to know the vocab size.
